/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sm.chr.iu;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 * Clase Lienzo2DImagen que extiende la funcionalidad de Lienzo2D con posibilidad de insertar imágenes. 
 * @author Chris
 */

public class Lienzo2DImagen extends Lienzo2D {
    
    // ATRIBUTOS
    private BufferedImage img;
    
    //MÉTODO GETIMG
     /**
     * Método para obtener la imagen.
     * @return img. 
     */
    public BufferedImage getImg() {
        return img;
    }
    
    // MÉTODO GETIMG CON BOOLEAN
    /**
     * Método para obtener la imagen.
     * @param drawVector. 
     * @return BufferedImage.
     */
    public BufferedImage getImg(boolean drawVector){
        if (drawVector){
            BufferedImage img_gformas = new BufferedImage(this.img.getWidth(), this.img.getHeight(), this.img.getType());
            this.paint(img_gformas.createGraphics());
            return img_gformas;
        }else{
          return getImg();
        }
    }

    // MÉTODO SETIMG
    /**
     * Método para modificar la imagen
     * @param img. 
     */
    public void setImg(BufferedImage img) {
        this.img = img;
        if(img!=null) {
            setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        }
    }
    
    // MÉTODO IMPLEMENTADO PAINCOMPONENT
    /**
     * Método para pintar la imagen
     * @param g. 
     */
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if (img != null) g.drawImage(img, 0, 0, this);
    }
     
    /**
     * Creates new form Lienzo2DImagen
     */
    
    // CONSTRUCTOR
    /**
     * Constructor de la clase LIENZO2DIMAGEN.
     */
    public Lienzo2DImagen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
