/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe_christian;
import java.awt.Color;
import sm.chr.iu.Lienzo2DImagen;

/**
 *
 * @author Chris
 */

public class VentanaInterna extends javax.swing.JInternalFrame {
    
    private final VentanaPrincipal ventanaPrinci;
    /**
     * Creates new form VentanaInterna
     * @param ventanaPadre
     */

    public VentanaInterna(VentanaPrincipal ventanaPadre) {
        this.ventanaPrinci = ventanaPadre;
        initComponents();
    }
    
    public Lienzo2DImagen getLienzo(){
        return lienzoImagen;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarrasDesplazamiento = new javax.swing.JScrollPane();
        lienzoImagen = new sm.chr.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lienzo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzoImagen.setBackground(new java.awt.Color(153, 153, 153));
        lienzoImagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoImagenMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzoImagenLayout = new javax.swing.GroupLayout(lienzoImagen);
        lienzoImagen.setLayout(lienzoImagenLayout);
        lienzoImagenLayout.setHorizontalGroup(
            lienzoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        lienzoImagenLayout.setVerticalGroup(
            lienzoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        BarrasDesplazamiento.setViewportView(lienzoImagen);

        getContentPane().add(BarrasDesplazamiento, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
       
        // BOTONES DE DIBUJO
        this.ventanaPrinci.botonRelleno.setSelected(lienzoImagen.isRelleno());
        this.ventanaPrinci.botonAlisar.setSelected(lienzoImagen.isAlisado());
        this.ventanaPrinci.botonEditar.setSelected(lienzoImagen.isEditar());
        this.ventanaPrinci.botonTransparencia.setSelected(lienzoImagen.isTransparente());
        this.ventanaPrinci.medidorGrosor.setValue(0);

        // BOTONES DE COLORES
        if (lienzoImagen.getColor() == Color.black) {
            this.ventanaPrinci.BotonNegro.setSelected(true);
        } 
        else if (lienzoImagen.getColor() == Color.white) {
            this.ventanaPrinci.BotonBlanco.setSelected(true);
        } 
        else if (lienzoImagen.getColor() == Color.yellow) {
            this.ventanaPrinci.BotonAmarillo.setSelected(true);
        } 
        else if (lienzoImagen.getColor() == Color.green) {
            this.ventanaPrinci.BotonVerde.setSelected(true);
        } 
        else if (lienzoImagen.getColor() == Color.red) {
            this.ventanaPrinci.BotonRojo.setSelected(true);
        } 
        else if (lienzoImagen.getColor() == Color.blue) {
            this.ventanaPrinci.BotonAzul.setSelected(true);
        }
                
        // BOTONES DE FORMA
        switch (lienzoImagen.getForma()) {
            
            case PUNTO:
                this.ventanaPrinci.BotonDibujarPunto.setSelected(true);
                break;
                
            case ELIPSE:
                this.ventanaPrinci.BotonDibujarElipse.setSelected(true);
                break;
                
            case RECTANGULO:
                this.ventanaPrinci.BotonDibujarRectangulo.setSelected(true);
                break;
                
            case LINEA:
                this.ventanaPrinci.BotonDibujarLinea.setSelected(true);
                break;
                
            case ROTODOS:
                this.ventanaPrinci.BotonRotoDos.setSelected(true);
                break;
                
            case GP:
                this.ventanaPrinci.BotonGP.setSelected(true);
                break;
                
            case CURVA:
                this.ventanaPrinci.BotonCurva.setSelected(true);
                break;
        }

        repaint();
 
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved

    }//GEN-LAST:event_lienzoMouseMoved

    private void lienzoImagenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoImagenMouseMoved
        // TODO add your handling code here:
        String pos = "(X: " + evt.getX() + " / Y: " + evt.getY() + ")";
        this.ventanaPrinci.PanelXY.setText(pos);
        
    }//GEN-LAST:event_lienzoImagenMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BarrasDesplazamiento;
    private sm.chr.iu.Lienzo2DImagen lienzoImagen;
    // End of variables declaration//GEN-END:variables
}
